# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ApplicationWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 480)
        Form.setMinimumSize(QtCore.QSize(800, 480))
        Form.setMaximumSize(QtCore.QSize(800, 480))
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 815, 451))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_5 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_5.setMinimumSize(QtCore.QSize(400, 140))
        self.frame_5.setMaximumSize(QtCore.QSize(400, 140))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.MultiMqlWidget = MultiMqlWidget(self.frame_5)
        self.MultiMqlWidget.setGeometry(QtCore.QRect(0, 20, 400, 120))
        self.MultiMqlWidget.setMaximumSize(QtCore.QSize(400, 120))
        self.MultiMqlWidget.setObjectName("MultiMqlWidget")
        self.label_graph_name = QtWidgets.QLabel(self.frame_5)
        self.label_graph_name.setGeometry(QtCore.QRect(0, 0, 70, 20))
        self.label_graph_name.setStyleSheet("font: 57 10pt \"Quicksand Medium\";\n"
"color: rgb(0, 255, 255);")
        self.label_graph_name.setObjectName("label_graph_name")
        self.gridLayout.addWidget(self.frame_5, 2, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_4.setMinimumSize(QtCore.QSize(400, 140))
        self.frame_4.setMaximumSize(QtCore.QSize(400, 140))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setLineWidth(1)
        self.frame_4.setObjectName("frame_4")
        self.SoilMqlWidget = SoilMqlWidget(self.frame_4)
        self.SoilMqlWidget.setEnabled(True)
        self.SoilMqlWidget.setGeometry(QtCore.QRect(0, 20, 400, 120))
        self.SoilMqlWidget.setMinimumSize(QtCore.QSize(400, 120))
        self.SoilMqlWidget.setMaximumSize(QtCore.QSize(400, 120))
        self.SoilMqlWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.SoilMqlWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.SoilMqlWidget.setObjectName("SoilMqlWidget")
        self.label_10 = QtWidgets.QLabel(self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 70, 20))
        self.label_10.setMaximumSize(QtCore.QSize(70, 20))
        self.label_10.setStyleSheet("font: 57 10pt \"Quicksand Medium\";\n"
"color: rgb(0, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.frame_4, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(125, 51))
        self.label.setMaximumSize(QtCore.QSize(125, 51))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(125, 51))
        self.label_3.setMaximumSize(QtCore.QSize(125, 51))
        self.label_3.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(125, 51))
        self.label_4.setMaximumSize(QtCore.QSize(125, 51))
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_integral_temp_standard = QtWidgets.QLabel(self.layoutWidget)
        self.label_integral_temp_standard.setMinimumSize(QtCore.QSize(0, 24))
        self.label_integral_temp_standard.setStyleSheet("font: 57 14pt \"Quicksand Medium\";\n"
"color: rgb(0, 255, 127);")
        self.label_integral_temp_standard.setText("")
        self.label_integral_temp_standard.setAlignment(QtCore.Qt.AlignCenter)
        self.label_integral_temp_standard.setObjectName("label_integral_temp_standard")
        self.horizontalLayout_7.addWidget(self.label_integral_temp_standard)
        self.label_temp_standard = QtWidgets.QLabel(self.layoutWidget)
        self.label_temp_standard.setMinimumSize(QtCore.QSize(0, 24))
        self.label_temp_standard.setStyleSheet("font: 57 14pt \"Quicksand Medium\";\n"
"color: rgb(0, 255, 127);")
        self.label_temp_standard.setText("")
        self.label_temp_standard.setAlignment(QtCore.Qt.AlignCenter)
        self.label_temp_standard.setObjectName("label_temp_standard")
        self.horizontalLayout_7.addWidget(self.label_temp_standard)
        self.label_humidity_standard = QtWidgets.QLabel(self.layoutWidget)
        self.label_humidity_standard.setMinimumSize(QtCore.QSize(0, 24))
        self.label_humidity_standard.setStyleSheet("font: 57 14pt \"Quicksand Medium\";\n"
"color: rgb(0, 255, 127);")
        self.label_humidity_standard.setText("")
        self.label_humidity_standard.setAlignment(QtCore.Qt.AlignCenter)
        self.label_humidity_standard.setObjectName("label_humidity_standard")
        self.horizontalLayout_7.addWidget(self.label_humidity_standard)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lcdNumber_integral_temp = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcdNumber_integral_temp.setMinimumSize(QtCore.QSize(125, 50))
        self.lcdNumber_integral_temp.setMaximumSize(QtCore.QSize(125, 50))
        self.lcdNumber_integral_temp.setObjectName("lcdNumber_integral_temp")
        self.horizontalLayout_2.addWidget(self.lcdNumber_integral_temp)
        self.label_temp = QtWidgets.QLabel(self.layoutWidget)
        self.label_temp.setMinimumSize(QtCore.QSize(125, 50))
        self.label_temp.setMaximumSize(QtCore.QSize(125, 50))
        self.label_temp.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_temp.setStyleSheet("font: 57 14pt \"Quicksand Medium\";\n"
"color: rgb(255, 0, 0);")
        self.label_temp.setText("")
        self.label_temp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_temp.setObjectName("label_temp")
        self.horizontalLayout_2.addWidget(self.label_temp)
        self.label_humidity = QtWidgets.QLabel(self.layoutWidget)
        self.label_humidity.setMinimumSize(QtCore.QSize(125, 50))
        self.label_humidity.setMaximumSize(QtCore.QSize(125, 50))
        self.label_humidity.setStyleSheet("font: 57 14pt \"Quicksand Medium\";\n"
"color: rgb(0, 170, 255);")
        self.label_humidity.setText("")
        self.label_humidity.setTextFormat(QtCore.Qt.AutoText)
        self.label_humidity.setAlignment(QtCore.Qt.AlignCenter)
        self.label_humidity.setObjectName("label_humidity")
        self.horizontalLayout_2.addWidget(self.label_humidity)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_3.setMinimumSize(QtCore.QSize(300, 140))
        self.frame_3.setMaximumSize(QtCore.QSize(300, 140))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 100, 20))
        self.label_6.setMinimumSize(QtCore.QSize(100, 20))
        self.label_6.setMaximumSize(QtCore.QSize(100, 20))
        self.label_6.setStyleSheet("font: 10pt \"Quicksand\";\n"
"color: rgb(0, 255, 255);")
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setObjectName("label_6")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 30, 281, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_13.setMinimumSize(QtCore.QSize(60, 20))
        self.label_13.setMaximumSize(QtCore.QSize(60, 20))
        self.label_13.setStyleSheet("font: 8pt \"Quicksand\";\n"
"color: rgb(117, 117, 117);")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        self.progressBar_tank_capacity = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar_tank_capacity.setMinimumSize(QtCore.QSize(150, 20))
        self.progressBar_tank_capacity.setMaximumSize(QtCore.QSize(150, 20))
        self.progressBar_tank_capacity.setProperty("value", 0)
        self.progressBar_tank_capacity.setObjectName("progressBar_tank_capacity")
        self.horizontalLayout_4.addWidget(self.progressBar_tank_capacity)
        spacerItem = QtWidgets.QSpacerItem(5, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(60, 20))
        self.label_7.setMaximumSize(QtCore.QSize(60, 20))
        self.label_7.setStyleSheet("font: 8pt \"Quicksand\";\n"
"color: rgb(117, 117, 117);")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.progressBar_soil = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar_soil.setMinimumSize(QtCore.QSize(150, 20))
        self.progressBar_soil.setMaximumSize(QtCore.QSize(150, 20))
        self.progressBar_soil.setProperty("value", 0)
        self.progressBar_soil.setObjectName("progressBar_soil")
        self.horizontalLayout_3.addWidget(self.progressBar_soil)
        self.label_soil_standard = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_soil_standard.setStyleSheet("font: 57 14pt \"Quicksand Medium\";\n"
"color: rgb(0, 255, 127);")
        self.label_soil_standard.setText("")
        self.label_soil_standard.setObjectName("label_soil_standard")
        self.horizontalLayout_3.addWidget(self.label_soil_standard)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.gridLayout.addWidget(self.frame_3, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.layoutWidget)
        self.frame_2.setMinimumSize(QtCore.QSize(300, 140))
        self.frame_2.setMaximumSize(QtCore.QSize(300, 140))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 100, 20))
        self.label_8.setMinimumSize(QtCore.QSize(100, 20))
        self.label_8.setMaximumSize(QtCore.QSize(100, 20))
        self.label_8.setStyleSheet("font: 10pt \"Quicksand\";\n"
"color: rgb(0, 255, 255);")
        self.label_8.setTextFormat(QtCore.Qt.AutoText)
        self.label_8.setObjectName("label_8")
        self.textBrowser_state = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser_state.setGeometry(QtCore.QRect(0, 20, 300, 120))
        self.textBrowser_state.setMaximumSize(QtCore.QSize(300, 120))
        self.textBrowser_state.setStyleSheet("font: 57 8pt \"Quicksand Medium\";\n"
"color: rgb(140, 140, 140);")
        self.textBrowser_state.setObjectName("textBrowser_state")
        self.gridLayout.addWidget(self.frame_2, 2, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 2, 1, 1)
        self.frame = QtWidgets.QFrame(self.layoutWidget)
        self.frame.setMinimumSize(QtCore.QSize(300, 125))
        self.frame.setMaximumSize(QtCore.QSize(300, 125))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 100, 20))
        self.label_9.setMinimumSize(QtCore.QSize(100, 20))
        self.label_9.setMaximumSize(QtCore.QSize(100, 20))
        self.label_9.setStyleSheet("font: 10pt \"Quicksand\";\n"
"color: rgb(0, 255, 255);")
        self.label_9.setText("")
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setObjectName("label_9")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(0, 0, 100, 20))
        self.label_12.setMinimumSize(QtCore.QSize(100, 20))
        self.label_12.setMaximumSize(QtCore.QSize(100, 20))
        self.label_12.setStyleSheet("font: 10pt \"Quicksand\";\n"
"color: rgb(0, 255, 255);")
        self.label_12.setTextFormat(QtCore.Qt.AutoText)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_graph = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_graph.setMinimumSize(QtCore.QSize(60, 50))
        self.pushButton_graph.setMaximumSize(QtCore.QSize(60, 50))
        self.pushButton_graph.setStyleSheet("color: rgb(85, 255, 255);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../../../../.designer/backup/integral_temp.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_graph.setIcon(icon)
        self.pushButton_graph.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_graph.setObjectName("pushButton_graph")
        self.verticalLayout_3.addWidget(self.pushButton_graph)
        self.pushButton_debug = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_debug.setMinimumSize(QtCore.QSize(60, 50))
        self.pushButton_debug.setMaximumSize(QtCore.QSize(60, 50))
        self.pushButton_debug.setStyleSheet("color: rgb(0, 255, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../../../../../.designer/backup/temperature.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_debug.setIcon(icon1)
        self.pushButton_debug.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_debug.setObjectName("pushButton_debug")
        self.verticalLayout_3.addWidget(self.pushButton_debug)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 2, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_connect = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_connect.setMinimumSize(QtCore.QSize(60, 50))
        self.pushButton_connect.setMaximumSize(QtCore.QSize(60, 50))
        self.pushButton_connect.setStyleSheet("color: rgb(0, 255, 255);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../../../../../.designer/backup/update.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_connect.setIcon(icon2)
        self.pushButton_connect.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.verticalLayout_5.addWidget(self.pushButton_connect)
        self.pushButton_close = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_close.setMinimumSize(QtCore.QSize(60, 50))
        self.pushButton_close.setMaximumSize(QtCore.QSize(60, 50))
        self.pushButton_close.setStyleSheet("color: rgb(85, 255, 255);\n"
"font: 57 12pt \"Quicksand Medium\";")
        self.pushButton_close.setObjectName("pushButton_close")
        self.verticalLayout_5.addWidget(self.pushButton_close)
        self.gridLayout.addLayout(self.verticalLayout_5, 1, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_graph_name.setText(_translate("Form", "積算温度"))
        self.label_10.setText(_translate("Form", "土壌監視"))
        self.label.setText(_translate("Form", "積算温度"))
        self.label_3.setText(_translate("Form", "温度"))
        self.label_4.setText(_translate("Form", "湿度"))
        self.label_6.setText(_translate("Form", "パフォーマンス"))
        self.label_13.setText(_translate("Form", "タンク水量"))
        self.label_7.setText(_translate("Form", "土壌水分"))
        self.label_8.setText(_translate("Form", "動作履歴"))
        self.label_12.setText(_translate("Form", "植生映像"))
        self.pushButton_graph.setText(_translate("Form", "データ"))
        self.pushButton_debug.setText(_translate("Form", "監視"))
        self.pushButton_connect.setText(_translate("Form", "接続"))
        self.pushButton_close.setText(_translate("Form", "閉じる"))
from multimqlwidget import MultiMqlWidget
from soilmqlwidget import SoilMqlWidget
